spring.application.name=studyhub
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

firebase.storage.bucket=studyhub-db.appspot.com

# Cache Configuration (use simple in-memory cache for now (no Redis needed!)
spring.cache.type=simple


